language: node_js

script: node_modules/karma/bin/karma start karma.conf.js --single-run
    
before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install
    - npm run test

notifications:
  slack: otwangular2:FoXPtnPC1yCGFxuiLF01EnuD
  
branches:
only:
    - master

# Github deployment key
env:
    - secure:"4SUdaxNI3C85hRnIo1+B2pD/3kKu5YuynRNhFNzF7MQ4hpYzDq8Xdo4em3PJsfThueBQhpgM8Y4C/D4fmxybd4XrC06yDlFvpbXvg2CoXdJxGbWVyqYJzOxmq7Im0BTsh++66LS+HfvieKsC9KegM009hbR2Knx NG4XcV4huM0cH2HJgg8XgAkTzuwLP4Ffd0/+FErA0Uhp6wDZhLebhRx/K5E/EksQMJ4colaR7jcvHmAWlnZgRr4e/+RW2Lg0L3fRIeDEaFH1FUxGC+xLqKuuSzchaC3CP03LsywjJpiPj3V/0lMCBd0n1/nC68RQd81cnF15VG jB++WnQdwk3RmVZ0sOBcVmK9ghE9o/NcSr9vt0oTvCx4KuvVRu3L8VFkm6WnX4lFPirA3rZHYJgTOySK5X02Ghbte154XFox8voAkmi4l4XcrZJLtDhPm8uE/BH18A5eUgO3+HR7u00Evg1adNolP5FtIZ+KMoOElEaNI1IaoQ TOMUtwGsr6LWxowD3673IZp9E8Nqlxag7rt1b+hZn9qK7JYp6NXYDFXTEgDR7Auh3L6qL+eTuH4yVnaTjwQK2C9QDmZCF0="
    
    
after_success:
  - "curl -o /tmp/travis-automerge https://raw.githubusercontent.com/cdown/travis-automerge/master/travis-automerge"
  - "chmod a+x /tmp/travis-automerge"
  - "BRANCHES_TO_MERGE_REGEX='^development' BRANCH_TO_MERGE_INTO=master GITHUB_REPO=jovan1ivanovski/OPEN_Launcher /tmp/travis-automerge"

