#!/bin/bash -e


export GIT_COMMITTER_EMAIL='travis@travis'
export GIT_COMMITTER_NAME='Travis CI'

rm -rf out || exit 0;
mkdir out;

cd out

git clone "${GH_REF}" out

printf 'Checking out to master branch %s\n' >&2
git checkout master 

printf 'Merging development into master %s\n' >&2
git merge --ff-only origin/development

printf 'Pushing to %s\n' development %s\n' >&2

git push --force "https://${GH_TOKEN}@${GH_REF}" development:master> /dev/null 2>&1

